### ISSUE TITLE
PHP Split Function

### ISSUE THREAD

**Issue by darogan** [ewels/labrador#11]
As of PHP version 7.0.0 the split function has been removed (see http://php.net/manual/en/function.split.php)

Ubuntu 16.04 ships with 7.0.8 so reports.php is failing on lines 127 & 130

Suggested change:
 
    foreach(split(" ",$dataset['accession_geo']) as $geo)

to 

    foreach(preg_split(" ",$dataset['accession_geo']) as $geo)

**Comment by ewels** [comment]
Thanks @darogan! I'm on honeymoon and only on my phone until mid February so can't do much before then. If you submit a PR with the change I should be able to merge though.

Phil

**Comment by ewels** [comment]
ps. A regular expression doesn't seem to be necessary here, so `explode` is probably better. I imagine I used `split` mostly because that's what other languages call the function.. :)

**Comment by darogan** [comment]
Stop checking your emails if you are on your honeymoon! 

I'm just getting back into using Labrador to serve out NGS data. I have loads of new "features", but will wait until you are back before submitting any PRs. I seems to be working well, but I'll get a chance to iron out any bugs in the next few weeks.

**Comment by darogan** [comment]
My updates are here https://github.com/darogan/labrador, but no PRs until you are back.

**Comment by ewels** [comment]
Haha, ok - sounds good! 😂

**Comment by ewels** [comment]
Closed in #14
