### ISSUE TITLE
A lot of Security Issues

### ISSUE THREAD

**Issue by agrawalsmart7** [ewels/labrador#26]
Hi, I have seen a lot of security issues in the code. The issues contains the SQL Injection, SSRF, XSS.

It would be great if you can add security measures in those code.

**Comment by ewels** [comment]
Hi @agrawalsmart7,

I'm afraid that Labrador is no longer an actively maintained project (the last release was in 2014). I agree that it has plenty of security issues, but I'm afraid that I don't have the time to do anything about it.

Note that Labrador was designed to only over run on internal networks (without incoming connections). That's not a reason to not design with security in mind, but still.

Phil

**Comment by agrawalsmart7** [comment]
Thanks,! As I am experimenting my tool by scanning the source code, and that tool reported me vulnerabilities so I just quickly created an issue without looking the activeness.

**Comment by ewels** [comment]
No worries! Thanks :)
